#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; TMP_WORK_DIR="$2"

[[ -e "$TMP_WORK_DIR/LINK" ]] && cp "$TMP_WORK_DIR/LINK" "$DOKKU_ROOT/$APP"
